#!/bin/bash
# Vector Toolbox - macOS One-Click Installer

set -u

echo "========================================================"
echo "  Vector Toolbox - macOS 一键安装程序"
echo "  适配 Adobe Illustrator 2021 - 2026+ (v25.0 - v30.0+)"
echo "========================================================"
echo ""

SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
USER_HOME="$HOME"
if [ "$(id -u)" -eq 0 ] && [ -n "${SUDO_USER:-}" ]; then
    DETECTED_HOME="$(dscl . -read "/Users/$SUDO_USER" NFSHomeDirectory 2>/dev/null | awk '{print $2}')"
    if [ -n "$DETECTED_HOME" ]; then
        USER_HOME="$DETECTED_HOME"
    fi
fi

INSTALL_DIR="$USER_HOME/Library/Application Support/VectorToolbox"
MAIN_SCRIPT="$INSTALL_DIR/Vector-Toolbox.jsx"
APPLICATIONS_DIR="${VT_APPLICATIONS_DIR:-/Applications}"
FOUND=0
FAILED=0

copy_payload() {
    if [ "$SOURCE_DIR" = "$INSTALL_DIR" ]; then
        return 0
    fi

    mkdir -p "$INSTALL_DIR" || return 1
    for directory in core config scripts; do
        if [ ! -d "$SOURCE_DIR/$directory" ]; then
            echo "[!] 安装包缺少目录: $directory"
            return 1
        fi
        mkdir -p "$INSTALL_DIR/$directory" || return 1
        cp -R "$SOURCE_DIR/$directory/." "$INSTALL_DIR/$directory/" || return 1
    done

    for file in Vector-Toolbox.jsx Install-VectorToolbox.jsx version.json \
        install-windows.bat install-macos.sh update-windows.bat update-macos.sh LICENSE; do
        if [ ! -f "$SOURCE_DIR/$file" ]; then
            echo "[!] 安装包缺少文件: $file"
            return 1
        fi
        cp -f "$SOURCE_DIR/$file" "$INSTALL_DIR/$file" || return 1
    done

    chmod +x "$INSTALL_DIR/install-macos.sh" "$INSTALL_DIR/update-macos.sh" 2>/dev/null || true
}

echo "正在复制程序文件到稳定安装目录..."
echo "   -> $INSTALL_DIR"
if ! copy_payload || [ ! -f "$MAIN_SCRIPT" ]; then
    echo "[!] 无法复制程序文件到稳定安装目录。"
    exit 1
fi

JS_ROOT="$(printf '%s' "$INSTALL_DIR" | sed 's/\\/\\\\/g; s/"/\\"/g')"
JS_MAIN="$(printf '%s' "$MAIN_SCRIPT" | sed 's/\\/\\\\/g; s/"/\\"/g')"

install_to_dir() {
    local target_dir="$1"
    local app_dir="$2"
    local target_file="$target_dir/Vector-Toolbox.jsx"
    local proxy_file

    echo "[找到版本] $app_dir"
    echo "   -> 脚本目录: $target_dir"

    proxy_file="$(mktemp "${TMPDIR:-/tmp}/vector-toolbox-proxy.XXXXXX")" || {
        echo "   [!] 无法创建临时启动代理"
        FAILED=1
        return
    }

    cat > "$proxy_file" <<EOF
/**
 * Vector Toolbox Launcher Proxy
 * Auto-generated by install-macos.sh
 * Compatible with Adobe Illustrator 2021 - 2026+
 */
#target illustrator
#targetengine "VectorToolboxMainEngine"
\$.global.VECTOR_TOOLBOX_ROOT = "$JS_ROOT";
var targetFile = new File("$JS_MAIN");
if (targetFile.exists) {
    \$.evalFile(targetFile);
} else {
    alert("Vector Toolbox installation is incomplete. Run the installer again:\\n" + targetFile.fsName);
}
EOF

    if [ -w "$target_dir" ]; then
        cp -f "$proxy_file" "$target_file"
    elif command -v sudo >/dev/null 2>&1; then
        echo "   需要管理员权限写入 Illustrator 脚本菜单。"
        sudo cp -f "$proxy_file" "$target_file"
    else
        false
    fi
    local copy_status=$?
    rm -f "$proxy_file"

    if [ "$copy_status" -ne 0 ] || [ ! -f "$target_file" ]; then
        echo "   [!] 写入失败: $target_file"
        FAILED=1
        return
    fi

    echo "   [成功] $target_file"
    echo ""
    FOUND=1
}

echo "正在扫描 $APPLICATIONS_DIR 中 Adobe Illustrator 2021+ 安装目录..."
echo ""

for APP_DIR in "$APPLICATIONS_DIR"/Adobe\ Illustrator\ *; do
    if [ ! -d "$APP_DIR" ]; then
        continue
    fi

    for PRESETS_DIR in "$APP_DIR/Presets.localized" "$APP_DIR/Presets"; do
        if [ ! -d "$PRESETS_DIR" ]; then
            continue
        fi
        for LANG_DIR in "$PRESETS_DIR"/*; do
            if [ ! -d "$LANG_DIR" ]; then
                continue
            fi
            for SCRIPT_NAME in Scripts 脚本 指令檔 スクリプト 스크립트 Skrypty Skript; do
                if [ -d "$LANG_DIR/$SCRIPT_NAME" ]; then
                    install_to_dir "$LANG_DIR/$SCRIPT_NAME" "$APP_DIR"
                fi
            done
        done
    done

    if [ -d "$APP_DIR/Scripts" ]; then
        install_to_dir "$APP_DIR/Scripts" "$APP_DIR"
    fi
done

echo ""
if [ "$FOUND" -eq 1 ] && [ "$FAILED" -eq 0 ]; then
    echo "========================================================"
    echo "  安装完成：程序文件已固定保存，并写入启动菜单。"
    echo "  安装目录：$INSTALL_DIR"
    echo "  请重启 Illustrator，然后打开 文件 -> 脚本 -> Vector-Toolbox。"
    echo "========================================================"
    exit 0
fi

if [ "$FOUND" -eq 1 ]; then
    echo "[!] 仅部分目录安装成功，请检查上方失败项。"
else
    echo "[!] 未找到可写入的 Illustrator 脚本菜单目录。"
    echo "    也可在 Illustrator 中运行 Install-VectorToolbox.jsx。"
fi
exit 1
