@echo off
setlocal EnableExtensions DisableDelayedExpansion
chcp 65001 >nul

set "IS_ELEVATED_ARG=0"
set "NO_PAUSE=0"
for %%A in (%*) do (
    if /i "%%~A"=="--elevated" set "IS_ELEVATED_ARG=1"
    if /i "%%~A"=="--no-pause" set "NO_PAUSE=1"
)

if "%IS_ELEVATED_ARG%"=="1" goto :ElevationComplete

powershell -NoProfile -Command "$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent()); if ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { exit 0 }; exit 1"
if not errorlevel 1 goto :ElevationComplete

echo 正在请求管理员权限，以写入 Illustrator 的实际脚本菜单目录...
set "VT_INSTALLER_PATH=%~f0"
set "VT_NO_PAUSE=%NO_PAUSE%"
powershell -NoProfile -Command "$argsList = @('--elevated'); if ($env:VT_NO_PAUSE -eq '1') { $argsList += '--no-pause' }; try { $process = Start-Process -FilePath $env:VT_INSTALLER_PATH -ArgumentList $argsList -Verb RunAs -Wait -PassThru; exit $process.ExitCode } catch { Write-Host ('[!] 无法获取管理员权限: ' + $_.Exception.Message); exit 1 }"
exit /b %errorlevel%

:ElevationComplete
echo ========================================================
echo   Vector Toolbox - Windows 一键安装程序
echo   适配 Adobe Illustrator 2021 - 2026+ (v25.0 - v30.0+)
echo ========================================================
echo.

set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR_CLEAN=%SCRIPT_DIR:~0,-1%"
set "SCRIPT_DIR_JS=%SCRIPT_DIR_CLEAN:\=/%"
set "FOUND=0"
set "FAILED=0"

echo 正在扫描 Illustrator 安装目录中的本地化脚本菜单...
echo.

for /d %%A in ("C:\Program Files\Adobe\Adobe Illustrator*") do call :ScanIllustrator "%%A"
for /d %%A in ("C:\Program Files (x86)\Adobe\Adobe Illustrator*") do call :ScanIllustrator "%%A"
for /d %%A in ("D:\Program Files\Adobe\Adobe Illustrator*") do call :ScanIllustrator "%%A"
for /d %%A in ("D:\Adobe\Adobe Illustrator*") do call :ScanIllustrator "%%A"

echo.
if "%FOUND%"=="1" if "%FAILED%"=="0" (
    echo ========================================================
    echo   安装完成：已写入发现的 Illustrator 脚本菜单目录。
    echo   请完全退出并重新打开 Illustrator，然后点击：
    echo   文件 -^> 脚本 -^> Vector-Toolbox
    echo ========================================================
    call :MaybePause
    exit /b 0
)

if "%FOUND%"=="1" (
    echo [!] 仅部分目录安装成功，请检查上方失败项。
) else (
    echo [!] 未找到可写入的 Illustrator 本地化脚本菜单目录。
    echo     请确认已安装 Illustrator，或手动选择：
    echo     Adobe Illustrator ^<版本^>\Presets\^<语言^>\^<脚本目录^>
)
call :MaybePause
exit /b 1

:ScanPresetsRoot
set "PRESETS_ROOT=%~1"
set "APP_DIR=%~2"
if not exist "%PRESETS_ROOT%" exit /b 0

for /d %%L in ("%PRESETS_ROOT%\*") do (
    call :InstallIfExists "%%L\脚本" "%APP_DIR%"
    call :InstallIfExists "%%L\Scripts" "%APP_DIR%"
    call :InstallIfExists "%%L\指令檔" "%APP_DIR%"
    call :InstallIfExists "%%L\スクリプト" "%APP_DIR%"
    call :InstallIfExists "%%L\스크립트" "%APP_DIR%"
    call :InstallIfExists "%%L\Skrypty" "%APP_DIR%"
    call :InstallIfExists "%%L\Skript" "%APP_DIR%"
)
exit /b 0

:ScanIllustrator
if not exist "%~1" exit /b 0
call :ScanPresetsRoot "%~1\Presets" "%~1"
call :ScanPresetsRoot "%~1\Presets.localized" "%~1"
exit /b 0

:InstallIfExists
if not exist "%~1" exit /b 0
call :InstallToScriptDir "%~1" "%~2"
exit /b 0

:InstallToScriptDir
set "TARGET_DIR=%~1"
set "APP_DIR=%~2"
set "TARGET_FILE=%TARGET_DIR%\Vector-Toolbox.jsx"

set "VT_VERIFY_FILE=%TARGET_FILE%"
set "VT_EXPECTED_PATH=%SCRIPT_DIR_JS%/Vector-Toolbox.jsx"
echo [找到版本] %APP_DIR%
echo    -^> 脚本目录: %TARGET_DIR%

powershell -NoProfile -Command "$lines = @('/**', ' * Vector Toolbox Launcher Proxy', ' * Auto-generated by install-windows.bat', ' * Compatible with Adobe Illustrator 2021 - 2026+', ' */', '#target illustrator', '#targetengine \"VectorToolboxMainEngine\"', ('$.global.VECTOR_TOOLBOX_ROOT = \"' + $env:SCRIPT_DIR_JS + '\";'), ('var targetFile = new File(\"' + $env:VT_EXPECTED_PATH + '\");'), 'if (targetFile.exists) {', '    $.evalFile(targetFile);', '} else {', '    alert(\"Vector Toolbox main script was not found. Keep the project folder in place:\\n\" + targetFile.fsName);', '}'); try { [IO.File]::WriteAllLines($env:VT_VERIFY_FILE, $lines, (New-Object Text.UTF8Encoding($true))); exit 0 } catch { exit 1 }"
if errorlevel 1 (
    echo    [!] 写入失败: %TARGET_FILE%
    set "FAILED=1"
    echo.
    exit /b 0
)

powershell -NoProfile -Command "try { $content = [IO.File]::ReadAllText($env:VT_VERIFY_FILE); if ($content.Contains($env:VT_EXPECTED_PATH)) { exit 0 } } catch {}; exit 1"
if errorlevel 1 (
    echo    [!] 写入或校验失败: %TARGET_FILE%
    set "FAILED=1"
) else (
    echo    [成功] %TARGET_FILE%
    set "FOUND=1"
)
echo.
exit /b 0

:MaybePause
if "%NO_PAUSE%"=="0" pause
exit /b 0
