#!/bin/bash
# Vector Toolbox - macOS One-Click Installer
# Deeply adapted for Adobe Illustrator 2021, 2022, 2023, 2024, 2025, 2026+ (v25.0 - v30.0+)

echo "========================================================"
echo "  Vector Toolbox - macOS 一键安装程序"
echo "  适配 Adobe Illustrator 2021 - 2026+ (v25.0 - v30.0+)"
echo "========================================================"
echo ""

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
MAIN_SCRIPT="$DIR/Vector-Toolbox.jsx"
FOUND=0

echo "正在扫描 /Applications 中 Adobe Illustrator 2021+ 安装目录..."
echo ""

install_to_dir() {
    local target_dir="$1"
    local app_dir="$2"
    echo "[找到版本] $app_dir"
    echo "   -> 脚本目录: $target_dir"
    
    local target_file="$target_dir/Vector-Toolbox.jsx"
    cat <<EOF > "$target_file"
/**
 * Vector Toolbox Launcher Proxy
 * Auto-generated by install-macos.sh
 * Compatible with Adobe Illustrator 2021 - 2026+
 */
#target illustrator
#targetengine "VectorToolboxMainEngine"
\$.global.VECTOR_TOOLBOX_ROOT = "$DIR";
var targetFile = new File("$MAIN_SCRIPT");
if (targetFile.exists) {
    \$.evalFile(targetFile);
} else {
    alert("找不到 Vector Toolbox 主程序，请确认原目录未被移动:\n" + targetFile.fsName);
}
EOF
    echo "   [✓ 注入成功] $target_file"
    echo ""
    FOUND=1
}

for APP_DIR in /Applications/Adobe\ Illustrator\ *; do
    if [ -d "$APP_DIR" ]; then
        # Check Presets.localized
        if [ -d "$APP_DIR/Presets.localized" ]; then
            for LANG_DIR in "$APP_DIR/Presets.localized"/*; do
                if [ -d "$LANG_DIR/Scripts" ]; then
                    install_to_dir "$LANG_DIR/Scripts" "$APP_DIR"
                fi
            done
        fi

        # Check Presets
        if [ -d "$APP_DIR/Presets" ]; then
            for LANG_DIR in "$APP_DIR/Presets"/*; do
                if [ -d "$LANG_DIR/Scripts" ]; then
                    install_to_dir "$LANG_DIR/Scripts" "$APP_DIR"
                fi
            done
        fi

        # Check direct Scripts folder
        if [ -d "$APP_DIR/Scripts" ]; then
            install_to_dir "$APP_DIR/Scripts" "$APP_DIR"
        fi
    fi
done

echo ""
if [ "$FOUND" -eq 1 ]; then
    echo "========================================================"
    echo "  🎉 安装完成！已成功注入所有发现的 Illustrator 版本。"
    echo "  请重启 Adobe Illustrator，点击菜单："
    echo "  【文件 (File)】 -> 【脚本 (Scripts)】 -> 【Vector-Toolbox】 即可常驻启动。"
    echo "========================================================"
else
    echo "[!] 未能自动检测到 Illustrator 目录。"
    echo "您可以打开 Illustrator，使用 Cmd+F12 运行项目根目录下的 Install-VectorToolbox.jsx 进行交互式安装。"
fi
echo ""
