/**
 * Vector Toolbox - One-Click In-App Installer (一键安装器)
 * Deeply adapted for Adobe Illustrator 2021, 2022, 2023, 2024, 2025, 2026+
 */

#target illustrator

(function () {
    var sourceDir = new File($.fileName).parent;
    var mainScript = new File(sourceDir.fsName + "/Vector-Toolbox.jsx");

    if (!mainScript.exists) {
        alert("安装失败：找不到主程序 Vector-Toolbox.jsx，请确保安装脚本与项目文件位于同一目录！", "Vector Toolbox 安装程序");
        return;
    }

    // Folder.appPackage points inside Support Files on Windows. Walk upward until
    // the actual Illustrator install root containing Presets is found.
    function findInstallRoot(startDir) {
        var current = startDir;
        for (var depth = 0; current && depth < 8; depth++) {
            var presets = new Folder(current.fsName + "/Presets");
            var localizedPresets = new Folder(current.fsName + "/Presets.localized");
            if (presets.exists || localizedPresets.exists) {
                return current;
            }
            if (!current.parent || current.parent.fsName === current.fsName) {
                break;
            }
            current = current.parent;
        }
        return null;
    }

    var appPath = findInstallRoot(Folder.appPackage);
    if (!appPath) {
        alert("安装失败：无法从当前 Illustrator 定位 Presets 脚本目录。", "Vector Toolbox 安装程序");
        return;
    }

    var candidateFolders = [];
    var currentLocale = ($.locale || "").toLowerCase().replace(/-/g, "_");

    function addCandidate(folder, localeName) {
        candidateFolders.push({
            folder: folder,
            locale: (localeName || "").toLowerCase().replace(/-/g, "_")
        });
    }

    function findScriptsFolders(baseDir) {
        if (!baseDir || !baseDir.exists) return;

        // Check baseDir/Presets and baseDir/Presets.localized
        var presetsNames = ["Presets", "Presets.localized"];
        for (var p = 0; p < presetsNames.length; p++) {
            var pDir = new Folder(baseDir.fsName + "/" + presetsNames[p]);
            if (pDir.exists) {
                var langSubDirs = pDir.getFiles();
                var scriptDirNames = ["脚本", "Scripts", "指令檔", "スクリプト", "스크립트", "Skrypty", "Skript"];
                for (var s = 0; s < langSubDirs.length; s++) {
                    if (langSubDirs[s] instanceof Folder) {
                        for (var n = 0; n < scriptDirNames.length; n++) {
                            var scriptsDir = new Folder(langSubDirs[s].fsName + "/" + scriptDirNames[n]);
                            if (scriptsDir.exists) {
                                addCandidate(scriptsDir, langSubDirs[s].name);
                            }
                        }
                    }
                }
            }
        }
    }

    findScriptsFolders(appPath);

    var targetFolder = null;
    for (var c = 0; c < candidateFolders.length; c++) {
        if (candidateFolders[c].locale === currentLocale) {
            targetFolder = candidateFolders[c].folder;
            break;
        }
    }
    if (!targetFolder && candidateFolders.length > 0) {
        targetFolder = candidateFolders[0].folder;
    }
    if (!targetFolder) {
        var manualFolder = Folder.selectDialog("未能自动定位脚本目录，请手动选择 Illustrator 的 Presets/<语言>/<脚本目录>：");
        if (manualFolder) {
            targetFolder = manualFolder;
        } else {
            alert("安装已取消。", "Vector Toolbox 安装程序");
            return;
        }
    }

    // Create a launcher proxy script in Presets/Scripts/
    var forwarderFile = new File(targetFolder.fsName + "/Vector-Toolbox.jsx");
    var targetPathEscaped = mainScript.fsName.replace(/\\/g, "/");

    var rootPathEscaped = sourceDir.fsName.replace(/\\/g, "/");
    var launcherCode = "\uFEFF/**\n" +
        " * Vector Toolbox Launcher Proxy\n" +
        " * Auto-generated by Vector Toolbox Installer\n" +
        " * Compatible with Adobe Illustrator 2021 - 2026+\n" +
        " */\n" +
        "#target illustrator\n" +
        "#targetengine \"VectorToolboxMainEngine\"\n" +
        "$.global.VECTOR_TOOLBOX_ROOT = \"" + rootPathEscaped + "\";\n" +
        "var targetFile = new File(\"" + targetPathEscaped + "\");\n" +
        "if (targetFile.exists) {\n" +
        "    $.evalFile(targetFile);\n" +
        "} else {\n" +
        "    alert(\"Vector Toolbox main script was not found. Keep the project folder in place:\\n\" + targetFile.fsName);\n" +
        "}\n";

    var isOpen = false;
    try {
        forwarderFile.encoding = "UTF-8";
        if (!forwarderFile.open("w")) {
            throw new Error(forwarderFile.error || "无法打开目标文件");
        }
        isOpen = true;
        if (!forwarderFile.write(launcherCode)) {
            throw new Error(forwarderFile.error || "写入启动代理失败");
        }
        if (!forwarderFile.close()) {
            throw new Error(forwarderFile.error || "关闭启动代理失败");
        }
        isOpen = false;
        if (!forwarderFile.exists || forwarderFile.length === 0) {
            throw new Error("启动代理写入后校验失败");
        }

        var aiVer = app.version || "2021+";
        alert("安装成功！\n\n" +
            "Vector Toolbox 启动代理已注入当前宿主环境 (Illustrator " + aiVer + ")：\n" + forwarderFile.fsName + "\n\n" +
            "【使用方式】\n" +
            "重启 Illustrator 后，在顶部菜单栏点击：\n" +
            "文件 (File) -> 脚本 (Scripts) -> Vector-Toolbox 即可直接启动！", "Vector Toolbox 安装完成");
    } catch (e) {
        if (isOpen) {
            try { forwarderFile.close(); } catch (closeError) {}
        }
        alert("写入脚本目录失败: " + (e.message || e.toString()) + "\n\nWindows 用户请运行 install-windows.bat 并允许管理员权限；macOS 用户请使用 install-macos.sh。", "安装失败");
    }
})();
